version: '3'



services:

  nats-server:
    image: nats:latest
    ports: 
      - "8222:8222"

  product-gateway:
    build: ./product-gateway
    ports:
      - "${PORT}:3000"
    volumes:
      -  ./product-gateway/src:/usr/src/app/src
    command: npm run dev

    environment:
      - PORT=3000
      - SERVER=nats://nats-server:4222
  
  product-microservice:
    build: ./Product-microservice
    ports:
      - "${PORTm}:3001"
    volumes:
      -  ./Product-microservice/src:/usr/src/app/src
    command: npm run dev

    environment:
      - PORT=3001
      - SERVER=nats://nats-server:4222
      - DATABASE_URL=postgresql://product_nzm1_user:ss5eM4mIswwEEo4vOES5PlKD7VJiLSPi@dpg-d1gt0kqli9vc73b32rog-a.oregon-postgres.render.com/product_nzm1
     
  orders-ms:
    depends_on: 
    - product-microservice
    build: ./orders-ms
    ports:
      - "${PORTo}:3002"
    volumes:
      -  ./orders-ms/src:/usr/src/app/src
    command: npm run dev

    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://microservice_g2e9_user:lQCQo63OxoE6pQWiGwkWEesYk1EtN3v1@dpg-d19qr2p5pdvs73a3anfg-a.oregon-postgres.render.com/microservice_g2e9
      - NATS_URL=nats://nats-server:4222 
     


    